"""
CauseEffectDiagram entity.

One Mermaid.js flowchart diagram per chapter, generated by GPT-4o-mini
from the chapter's topic content. Stored as a Mermaid source string and
rendered client-side as SVG — no server-side compilation required.
"""
from datetime import datetime
from ..extensions import db


class CauseEffectDiagram(db.Model):
    __tablename__ = 'cause_effect_diagram'

    diagram_id = db.Column('diagramId', db.Integer, primary_key=True, autoincrement=True)
    form_level = db.Column('formLevel', db.Integer, nullable=False)
    chapter_id = db.Column('chapterId', db.Integer, nullable=False)
    title = db.Column('title', db.String(255), nullable=False)
    mermaid_source = db.Column('mermaidSource', db.Text, nullable=False)
    generated_at = db.Column(
        'generatedAt', db.DateTime, nullable=False, default=datetime.utcnow
    )

    __table_args__ = (
        db.UniqueConstraint('formLevel', 'chapterId', name='uq_ced_chapter'),
        db.ForeignKeyConstraint(
            ['formLevel', 'chapterId'],
            ['chapter.formLevel', 'chapter.chapterId'],
            ondelete='CASCADE',
            name='fk_ced_chapter',
        ),
    )

    def to_dict(self) -> dict:
        return {
            'diagramId': self.diagram_id,
            'formLevel': self.form_level,
            'chapterId': self.chapter_id,
            'title': self.title,
            'mermaidSource': self.mermaid_source,
            'generatedAt': self.generated_at.isoformat(),
        }

    def __repr__(self) -> str:
        return f'<CauseEffectDiagram F{self.form_level}-Ch{self.chapter_id}>'
