"""
QuizService — per-attempt question snapshots + AI streaming generation.

Step 5 changes:
  - start_attempt() creates an attempt but does NOT generate questions.
    Generation happens in stream_questions() via SSE.
  - Questions are stored in attempt_question, never on the Quiz itself.
  - submit/save/get logic is updated to use attempt_question.
"""
from typing import Iterator, List, Optional

from ..extensions import db
from ..models import Quiz, QuizAttempt
from ..repositories import (
    QuizRepository,
    QuizAttemptRepository,
    AttemptQuestionRepository,
    TopicPageRepository,
    StudentRepository,
)
from ..utils.errors import NotFoundError, ForbiddenError, ValidationError
from .ai import OllamaQuestionGenerator

# Maximum pages to sample for quiz context (keeps context < generator's 8000-char cap
# while ensuring even coverage across the chapter, not just the first N pages)
_MAX_SAMPLE_PAGES = 12
_MAX_CONTEXT_CHARS = 7500


def _stratified_context(pages: list) -> str:
    """Sample pages evenly across the chapter and join them into context.

    Avoids the bias of a plain truncation (which only shows the first pages).
    """
    filled = [p for p in pages if p.text_content and p.text_content.strip()]
    if not filled:
        return ''

    if len(filled) <= _MAX_SAMPLE_PAGES:
        sampled = filled
    else:
        step = len(filled) / _MAX_SAMPLE_PAGES
        sampled = [filled[int(i * step)] for i in range(_MAX_SAMPLE_PAGES)]

    parts = []
    total = 0
    for p in sampled:
        chunk = p.text_content[:1500]  # cap per page to ensure variety
        if total + len(chunk) > _MAX_CONTEXT_CHARS:
            break
        parts.append(chunk)
        total += len(chunk)

    return '\n\n'.join(parts)


class QuizService:

    # ==================================================================
    # Read-side
    # ==================================================================

    @staticmethod
    def list_quizzes_for_student(
        student_id: int, form_level: Optional[int] = None
    ) -> List[dict]:
        quizzes = QuizRepository.list_all(form_level)
        if not quizzes:
            return []

        all_attempts = QuizAttemptRepository.list_for_student(student_id)
        by_quiz: dict[int, List[QuizAttempt]] = {}
        for a in all_attempts:
            by_quiz.setdefault(a.quiz_id, []).append(a)

        result = []
        for q in quizzes:
            attempts = by_quiz.get(q.quiz_id, [])
            submitted = [a for a in attempts if a.status == 'submitted']
            in_progress = next(
                (a for a in attempts if a.status == 'in_progress'), None
            )
            best = max(submitted, key=lambda a: (a.score or 0), default=None)

            d = q.to_summary_dict()
            d['hasInProgressAttempt'] = in_progress is not None
            d['inProgressAttemptId'] = in_progress.attempt_id if in_progress else None
            d['attemptCount'] = len(submitted)
            d['bestScore'] = best.score if best else None
            d['bestPercentage'] = (
                round((best.score / best.max_score) * 100, 2)
                if best and best.max_score else None
            )
            result.append(d)
        return result

    # ==================================================================
    # Attempt lifecycle
    # ==================================================================

    @staticmethod
    def start_attempt(student_id: int, quiz_id: int) -> dict:
        """Resume in-progress attempt, OR create a new pending attempt.

        Question generation does NOT happen here — call stream_questions()
        after this to populate the questions via SSE.
        """
        quiz = QuizRepository.get(quiz_id)
        if not quiz:
            raise NotFoundError(f'Quiz {quiz_id} not found.')

        existing = QuizAttemptRepository.find_in_progress(student_id, quiz_id)
        if existing:
            return QuizService._attempt_to_dict(existing, include_questions=True)

        attempt = QuizAttemptRepository.create(
            student_id=student_id,
            quiz_id=quiz_id,
            target_question_count=quiz.default_question_count,
        )
        StudentRepository.commit()
        return QuizService._attempt_to_dict(attempt, include_questions=True)

    @staticmethod
    def stream_questions(
        student_id: int, attempt_id: int
    ) -> Iterator[dict]:
        """Yield questions one-by-one as they're generated by Ollama.

        Each yielded dict is a 'question' event for the frontend SSE handler.
        Final event is 'done' or 'error'.
        """
        attempt = QuizService._fetch_owned_attempt(student_id, attempt_id)

        # Prevent double-generation: if another stream is already running
        # for this attempt, stream the existing questions out and stop.
        if attempt.generation_status == 'generating':
            for q in attempt.attempt_questions:
                yield {'event': 'question', 'question': q.to_student_dict()}
            yield {
                'event': 'done',
                'total': len(attempt.attempt_questions),
                'target': attempt.target_question_count,
            }
            return


        if attempt.status == 'submitted':
            yield {'event': 'error', 'message': 'This attempt is already submitted.'}
            return
        if attempt.generation_status == 'ready':
            # Already generated — just stream the existing questions out
            for q in attempt.attempt_questions:
                yield {'event': 'question', 'question': q.to_student_dict()}
            yield {'event': 'done', 'total': len(attempt.attempt_questions)}
            return

        existing_count = AttemptQuestionRepository.count_for_attempt(attempt_id)
        remaining = attempt.target_question_count - existing_count
        if remaining <= 0:
            yield {'event': 'done', 'total': existing_count}
            return

        # Build context from topic_page rows
        quiz = attempt.quiz
        if quiz.scope == 'bab':
            pages = TopicPageRepository.list_for_chapter(quiz.form_level, quiz.chapter_id)
        else:  # 'form' — mega quiz, all chapters
            from ..models import Chapter
            chapters = db.session.query(Chapter).filter_by(
                form_level=quiz.form_level
            ).all()
            pages = []
            for c in chapters:
                pages.extend(TopicPageRepository.list_for_chapter(c.form_level, c.chapter_id))

        if not pages:
            QuizAttemptRepository.set_generation_status(attempt, 'failed')
            StudentRepository.commit()
            yield {
                'event': 'error',
                'message': 'No KSSM source text available for this quiz scope. '
                           'Has the PDF been ingested?',
            }
            return

        context = _stratified_context(pages)

        # Stream from Ollama
        QuizAttemptRepository.set_generation_status(attempt, 'generating')
        StudentRepository.commit()

        generator = OllamaQuestionGenerator()
        order_offset = existing_count + 1
        produced = 0

        try:
            for gq in generator.generate_stream(context, remaining, language='bm'):
                aq = AttemptQuestionRepository.add(
                    attempt_id=attempt_id,
                    order_index=order_offset + produced,
                    stem=gq.stem,
                    options=gq.options,
                    correct_index=gq.correct_index,
                    explanation=gq.explanation,
                    points=gq.points,
                )
                StudentRepository.commit()
                produced += 1
                q_dict = aq.to_student_dict()
                q_dict['difficulty'] = gq.difficulty
                yield {'event': 'question', 'question': q_dict}
        except Exception as exc:
            QuizAttemptRepository.set_generation_status(attempt, 'failed')
            StudentRepository.commit()
            yield {'event': 'error', 'message': f'Generation failed: {exc}'}
            return

        # Mark ready (even if we got fewer than requested — partial success)
        if produced > 0:
            QuizAttemptRepository.set_generation_status(attempt, 'ready')
        else:
            QuizAttemptRepository.set_generation_status(attempt, 'failed')
        StudentRepository.commit()

        yield {
            'event': 'done',
            'total': existing_count + produced,
            'target': attempt.target_question_count,
        }

    @staticmethod
    def get_attempt(student_id: int, attempt_id: int) -> dict:
        attempt = QuizService._fetch_owned_attempt(student_id, attempt_id)
        return QuizService._attempt_to_dict(
            attempt,
            include_questions=True,
            include_review=(attempt.status == 'submitted'),
        )

    @staticmethod
    def save_answer(
        student_id: int,
        attempt_id: int,
        attempt_question_id: int,
        selected_index: Optional[int],
    ) -> dict:
        attempt = QuizService._fetch_owned_attempt(student_id, attempt_id)
        if attempt.status != 'in_progress':
            raise ForbiddenError('This attempt has been submitted already.')

        question = AttemptQuestionRepository.get(attempt_question_id)
        if not question or question.attempt_id != attempt_id:
            raise ValidationError(
                errors={'attemptQuestionId': 'Question does not belong to this attempt.'}
            )
        if selected_index is not None and not (0 <= selected_index <= 3):
            raise ValidationError(
                errors={'selectedIndex': 'Must be null or between 0 and 3.'}
            )

        ans = QuizAttemptRepository.upsert_answer(
            attempt_id, attempt_question_id, selected_index
        )
        StudentRepository.commit()
        return ans.to_dict()

    @staticmethod
    def submit_attempt(student_id: int, attempt_id: int) -> dict:
        attempt = QuizService._fetch_owned_attempt(student_id, attempt_id)
        if attempt.status == 'submitted':
            return QuizService._attempt_to_dict(
                attempt, include_questions=True, include_review=True
            )

        questions = attempt.attempt_questions
        if not questions:
            raise ValidationError(
                'Cannot submit an attempt with no generated questions.'
            )

        answers_by_qid = {
            a.attempt_question_id: a for a in QuizAttemptRepository.list_answers(attempt_id)
        }

        score = 0
        max_score = 0
        correct_count = 0

        for q in questions:
            max_score += q.points
            ans = answers_by_qid.get(q.attempt_question_id)
            if not ans:
                ans = QuizAttemptRepository.upsert_answer(
                    attempt_id, q.attempt_question_id, None
                )
            is_correct = ans.selected_index == q.correct_index
            ans.is_correct = is_correct
            if is_correct:
                score += q.points
                correct_count += 1

        QuizAttemptRepository.finalize(
            attempt, score=score, max_score=max_score,
            correct_count=correct_count, total_questions=len(questions),
        )
        StudentRepository.commit()
        return QuizService._attempt_to_dict(
            attempt, include_questions=True, include_review=True
        )

    @staticmethod
    def list_my_attempts(
        student_id: int, quiz_id: Optional[int] = None
    ) -> List[dict]:
        attempts = QuizAttemptRepository.list_for_student(student_id, quiz_id)
        return [a.to_summary_dict() for a in attempts]

    # ==================================================================
    # Internals
    # ==================================================================

    @staticmethod
    def _fetch_owned_attempt(student_id: int, attempt_id: int) -> QuizAttempt:
        attempt = QuizAttemptRepository.get(attempt_id)
        if not attempt:
            raise NotFoundError(f'Attempt {attempt_id} not found.')
        if attempt.student_id != student_id:
            raise ForbiddenError('This attempt belongs to another student.')
        return attempt

    @staticmethod
    def _attempt_to_dict(
        attempt: QuizAttempt,
        include_questions: bool = False,
        include_review: bool = False,
    ) -> dict:
        d = attempt.to_summary_dict()
        quiz = attempt.quiz
        d['quiz'] = quiz.to_summary_dict() if quiz else None

        if include_questions and quiz:
            answers = {a.attempt_question_id: a for a in attempt.answers}
            questions = []
            for q in attempt.attempt_questions:
                base = q.to_review_dict() if include_review else q.to_student_dict()
                ans = answers.get(q.attempt_question_id)
                base['selectedIndex'] = ans.selected_index if ans else None
                base['isCorrect'] = ans.is_correct if (ans and include_review) else None
                questions.append(base)
            d['questions'] = questions

        return d