"""drop topic.content, add pdf_path/total_pages, add topic_page

Revision ID: 00c8e847f4d6
Revises: 9a7d64e08a25
Create Date: 2026-05-12 15:37:15.665264

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '00c8e847f4d6'
down_revision = '9a7d64e08a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic_page',
    sa.Column('topicPageId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('topicId', sa.Integer(), nullable=False),
    sa.Column('pageNumber', sa.Integer(), nullable=False),
    sa.Column('textContent', sa.Text(), nullable=False),
    sa.Column('wordCount', sa.Integer(), nullable=False),
    sa.CheckConstraint('pageNumber >= 1', name='ck_page_number_positive'),
    sa.ForeignKeyConstraint(['topicId'], ['topic.topicId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topicPageId'),
    sa.UniqueConstraint('topicId', 'pageNumber', name='uq_topic_page')
    )
    with op.batch_alter_table('topic_page', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_topic_page_topicId'), ['topicId'], unique=False)

    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdfPath', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('totalPages', sa.Integer(), nullable=True))
        batch_op.drop_column('content')
        batch_op.drop_column('pdfReference')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('topic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pdfReference', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True))
        batch_op.add_column(sa.Column('content', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False))
        batch_op.drop_column('totalPages')
        batch_op.drop_column('pdfPath')

    with op.batch_alter_table('topic_page', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_topic_page_topicId'))

    op.drop_table('topic_page')
    # ### end Alembic commands ###
