"""step6: chat_conversation and chat_message for AI Tutor

Revision ID: 2d282294350e
Revises: a0798af7eb5d
Create Date: 2026-05-16 19:49:28.959028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d282294350e'
down_revision = 'a0798af7eb5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_conversation',
    sa.Column('conversationId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('topicId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studentId'], ['student.studentId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topicId'], ['topic.topicId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('conversationId'),
    sa.UniqueConstraint('studentId', 'topicId', name='uq_chat_student_topic')
    )
    with op.batch_alter_table('chat_conversation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_conversation_studentId'), ['studentId'], unique=False)
        batch_op.create_index(batch_op.f('ix_chat_conversation_topicId'), ['topicId'], unique=False)

    op.create_table('chat_message',
    sa.Column('messageId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversationId', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('sourcePageStart', sa.Integer(), nullable=True),
    sa.Column('sourcePageEnd', sa.Integer(), nullable=True),
    sa.Column('validationStatus', sa.String(length=16), nullable=False),
    sa.Column('validationWarning', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role IN ('user', 'assistant')", name='ck_chat_msg_role'),
    sa.CheckConstraint("validationStatus IN ('ok', 'warned', 'na')", name='ck_chat_msg_validation'),
    sa.ForeignKeyConstraint(['conversationId'], ['chat_conversation.conversationId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('messageId')
    )
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_chat_message_conversationId'), ['conversationId'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat_message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_message_conversationId'))

    op.drop_table('chat_message')
    with op.batch_alter_table('chat_conversation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chat_conversation_topicId'))
        batch_op.drop_index(batch_op.f('ix_chat_conversation_studentId'))

    op.drop_table('chat_conversation')
    # ### end Alembic commands ###
