"""add quiz, quiz_question, quiz_attempt, attempt_answer

Revision ID: 3c29491b23bb
Revises: 00c8e847f4d6
Create Date: 2026-05-13 00:25:47.959376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c29491b23bb'
down_revision = '00c8e847f4d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('quiz',
    sa.Column('quizId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('formLevel', sa.Integer(), nullable=False),
    sa.Column('chapterId', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=True),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('updatedAt', sa.DateTime(), nullable=False),
    sa.CheckConstraint("scope IN ('bab', 'form')", name='ck_quiz_scope'),
    sa.CheckConstraint('formLevel IN (4, 5)', name='ck_quiz_form_level'),
    sa.PrimaryKeyConstraint('quizId'),
    sa.UniqueConstraint('formLevel', 'chapterId', 'scope', name='uq_quiz_scope')
    )
    op.create_table('quiz_attempt',
    sa.Column('attemptId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('quizId', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('startedAt', sa.DateTime(), nullable=False),
    sa.Column('submittedAt', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('maxScore', sa.Integer(), nullable=True),
    sa.Column('correctCount', sa.Integer(), nullable=True),
    sa.Column('totalQuestions', sa.Integer(), nullable=True),
    sa.CheckConstraint("status IN ('in_progress', 'submitted')", name='ck_attempt_status'),
    sa.ForeignKeyConstraint(['quizId'], ['quiz.quizId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studentId'], ['student.studentId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attemptId')
    )
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_attempt_quizId'), ['quizId'], unique=False)
        batch_op.create_index(batch_op.f('ix_quiz_attempt_studentId'), ['studentId'], unique=False)

    op.create_table('quiz_question',
    sa.Column('questionId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('quizId', sa.Integer(), nullable=False),
    sa.Column('orderIndex', sa.Integer(), nullable=False),
    sa.Column('stem', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correctIndex', sa.Integer(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.CheckConstraint('correctIndex BETWEEN 0 AND 3', name='ck_correct_idx'),
    sa.CheckConstraint('points >= 0', name='ck_points_nonneg'),
    sa.ForeignKeyConstraint(['quizId'], ['quiz.quizId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('questionId'),
    sa.UniqueConstraint('quizId', 'orderIndex', name='uq_question_order')
    )
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_quiz_question_quizId'), ['quizId'], unique=False)

    op.create_table('attempt_answer',
    sa.Column('attemptId', sa.Integer(), nullable=False),
    sa.Column('questionId', sa.Integer(), nullable=False),
    sa.Column('selectedIndex', sa.Integer(), nullable=True),
    sa.Column('isCorrect', sa.Boolean(), nullable=True),
    sa.Column('answeredAt', sa.DateTime(), nullable=False),
    sa.CheckConstraint('selectedIndex IS NULL OR selectedIndex BETWEEN 0 AND 3', name='ck_answer_idx'),
    sa.ForeignKeyConstraint(['attemptId'], ['quiz_attempt.attemptId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['questionId'], ['quiz_question.questionId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attemptId', 'questionId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempt_answer')
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_question_quizId'))

    op.drop_table('quiz_question')
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_quiz_attempt_studentId'))
        batch_op.drop_index(batch_op.f('ix_quiz_attempt_quizId'))

    op.drop_table('quiz_attempt')
    op.drop_table('quiz')
    # ### end Alembic commands ###
