"""add_student_quiz_preferences_and_attempt_difficulty_target

Revision ID: 729813a0518e
Revises: 85f5d81c2298
Create Date: 2026-06-05 17:22:11.537454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '729813a0518e'
down_revision = '85f5d81c2298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('difficultyTarget', sa.String(length=16), nullable=True))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quizDifficulty', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('questionsPerQuiz', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('questionsPerQuiz')
        batch_op.drop_column('quizDifficulty')

    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.drop_column('difficultyTarget')

    # ### end Alembic commands ###
