"""essay_practice_tables

Revision ID: 85f5d81c2298
Revises: 2d282294350e
Create Date: 2026-06-05 11:34:29.386562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85f5d81c2298'
down_revision = '2d282294350e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('essay_question',
    sa.Column('questionId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('questionText', sa.Text(), nullable=False),
    sa.Column('questionType', sa.String(length=16), nullable=False),
    sa.Column('formLevel', sa.Integer(), nullable=False),
    sa.Column('chapterId', sa.Integer(), nullable=False),
    sa.Column('subQuestion', sa.String(length=8), nullable=True),
    sa.Column('maxMarks', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=16), nullable=False),
    sa.Column('markingSchemeJson', sa.JSON(), nullable=False),
    sa.Column('modelAnswer', sa.Text(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.CheckConstraint("difficulty IN ('easy', 'medium', 'hard')", name='ck_eq_difficulty'),
    sa.CheckConstraint("questionType IN ('struktur', 'esei')", name='ck_eq_question_type'),
    sa.CheckConstraint('formLevel IN (4, 5)', name='ck_eq_form_level'),
    sa.ForeignKeyConstraint(['formLevel', 'chapterId'], ['chapter.formLevel', 'chapter.chapterId'], name='fk_eq_chapter', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('questionId')
    )
    with op.batch_alter_table('essay_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_essay_question_chapterId'), ['chapterId'], unique=False)
        batch_op.create_index(batch_op.f('ix_essay_question_formLevel'), ['formLevel'], unique=False)

    op.create_table('essay_attempt',
    sa.Column('attemptId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('questionId', sa.Integer(), nullable=False),
    sa.Column('responseText', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('gradingStatus', sa.String(length=16), nullable=False),
    sa.Column('isNoteForm', sa.Boolean(), nullable=True),
    sa.Column('arasLevel', sa.Integer(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('maxScore', sa.Integer(), nullable=True),
    sa.Column('matchedCodesJson', sa.JSON(), nullable=True),
    sa.Column('feedbackJson', sa.JSON(), nullable=True),
    sa.Column('startedAt', sa.DateTime(), nullable=False),
    sa.Column('submittedAt', sa.DateTime(), nullable=True),
    sa.CheckConstraint("gradingStatus IN ('pending', 'grading', 'done', 'failed')", name='ck_ea_grading_status'),
    sa.CheckConstraint("status IN ('draft', 'submitted', 'graded')", name='ck_ea_status'),
    sa.ForeignKeyConstraint(['questionId'], ['essay_question.questionId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['studentId'], ['student.studentId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attemptId')
    )
    with op.batch_alter_table('essay_attempt', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_essay_attempt_questionId'), ['questionId'], unique=False)
        batch_op.create_index(batch_op.f('ix_essay_attempt_studentId'), ['studentId'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('essay_attempt', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essay_attempt_studentId'))
        batch_op.drop_index(batch_op.f('ix_essay_attempt_questionId'))

    op.drop_table('essay_attempt')
    with op.batch_alter_table('essay_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_essay_question_formLevel'))
        batch_op.drop_index(batch_op.f('ix_essay_question_chapterId'))

    op.drop_table('essay_question')
    # ### end Alembic commands ###
