"""initial schema

Revision ID: 9a7d64e08a25
Revises: 
Create Date: 2026-05-11 07:28:02.272462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7d64e08a25'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chapter',
    sa.Column('formLevel', sa.Integer(), nullable=False),
    sa.Column('chapterId', sa.Integer(), nullable=False),
    sa.Column('chapterName', sa.String(length=255), nullable=False),
    sa.CheckConstraint('chapterId >= 1', name='ck_chapter_id_positive'),
    sa.CheckConstraint('formLevel IN (4, 5)', name='ck_chapter_form_level'),
    sa.PrimaryKeyConstraint('formLevel', 'chapterId')
    )
    op.create_table('student',
    sa.Column('studentId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('passwordHash', sa.String(length=255), nullable=False),
    sa.Column('fullName', sa.String(length=100), nullable=False),
    sa.Column('formLevel', sa.Integer(), nullable=False),
    sa.Column('registrationDate', sa.Date(), nullable=False),
    sa.CheckConstraint('formLevel IN (4, 5)', name='ck_student_form_level'),
    sa.PrimaryKeyConstraint('studentId')
    )
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_email'), ['email'], unique=True)

    op.create_table('learning_progress',
    sa.Column('progressId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('lastUpdated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studentId'], ['student.studentId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progressId'),
    sa.UniqueConstraint('studentId')
    )
    op.create_table('password_reset_token',
    sa.Column('tokenId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('tokenHash', sa.String(length=64), nullable=False),
    sa.Column('expiresAt', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['studentId'], ['student.studentId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('tokenId'),
    sa.UniqueConstraint('tokenHash')
    )
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_reset_token_studentId'), ['studentId'], unique=False)

    op.create_table('session',
    sa.Column('sessionId', sa.String(length=128), nullable=False),
    sa.Column('studentId', sa.Integer(), nullable=False),
    sa.Column('createdAt', sa.DateTime(), nullable=False),
    sa.Column('lastActivity', sa.DateTime(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['studentId'], ['student.studentId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('sessionId')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_studentId'), ['studentId'], unique=False)

    op.create_table('topic',
    sa.Column('topicId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formLevel', sa.Integer(), nullable=False),
    sa.Column('chapterId', sa.Integer(), nullable=False),
    sa.Column('topicName', sa.String(length=255), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('estimatedDurationMinutes', sa.Integer(), nullable=True),
    sa.Column('pdfReference', sa.String(length=500), nullable=True),
    sa.CheckConstraint('formLevel IN (4, 5)', name='ck_topic_form_level'),
    sa.ForeignKeyConstraint(['formLevel', 'chapterId'], ['chapter.formLevel', 'chapter.chapterId'], name='fk_topic_chapter'),
    sa.PrimaryKeyConstraint('topicId'),
    sa.UniqueConstraint('formLevel', 'chapterId', 'topicName', name='uq_topic_form_chapter_name')
    )
    op.create_table('bookmarked_topic',
    sa.Column('progressId', sa.Integer(), nullable=False),
    sa.Column('topicId', sa.Integer(), nullable=False),
    sa.Column('bookmarkedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['progressId'], ['learning_progress.progressId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topicId'], ['topic.topicId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progressId', 'topicId')
    )
    op.create_table('completed_topic',
    sa.Column('progressId', sa.Integer(), nullable=False),
    sa.Column('topicId', sa.Integer(), nullable=False),
    sa.Column('completedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['progressId'], ['learning_progress.progressId'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topicId'], ['topic.topicId'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('progressId', 'topicId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('completed_topic')
    op.drop_table('bookmarked_topic')
    op.drop_table('topic')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_studentId'))

    op.drop_table('session')
    with op.batch_alter_table('password_reset_token', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_password_reset_token_studentId'))

    op.drop_table('password_reset_token')
    op.drop_table('learning_progress')
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_email'))

    op.drop_table('student')
    op.drop_table('chapter')
    # ### end Alembic commands ###
