"""step5: per-attempt questions for AI generation

Revision ID: a0798af7eb5d
Revises: 3c29491b23bb
Create Date: 2026-05-14 05:28:25.819504

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0798af7eb5d'
down_revision = '3c29491b23bb'
branch_labels = None
depends_on = None


def upgrade():
    # 1. Create new attempt_question table
    op.create_table('attempt_question',
        sa.Column('attemptQuestionId', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('attemptId', sa.Integer(), nullable=False),
        sa.Column('orderIndex', sa.Integer(), nullable=False),
        sa.Column('stem', sa.Text(), nullable=False),
        sa.Column('options', sa.JSON(), nullable=False),
        sa.Column('correctIndex', sa.Integer(), nullable=False),
        sa.Column('explanation', sa.Text(), nullable=True),
        sa.Column('points', sa.Integer(), nullable=False),
        sa.CheckConstraint('correctIndex BETWEEN 0 AND 3', name='ck_aq_correct_idx'),
        sa.ForeignKeyConstraint(['attemptId'], ['quiz_attempt.attemptId'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('attemptQuestionId'),
        sa.UniqueConstraint('attemptId', 'orderIndex', name='uq_attempt_question_order')
    )
    with op.batch_alter_table('attempt_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attempt_question_attemptId'), ['attemptId'], unique=False)

    # 2. Wipe any old test rows so the schema change doesn't fight FK constraints
    op.execute('DELETE FROM attempt_answer')
    op.execute('DELETE FROM quiz_attempt')

    # 3. First, swap attempt_answer's FK. The OLD FK points at quiz_question —
    #    we must drop it BEFORE we can drop quiz_question's indexes/table.
    with op.batch_alter_table('attempt_answer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('attempt_answer_ibfk_2'), type_='foreignkey')
        batch_op.add_column(sa.Column('attemptQuestionId', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(
            'fk_attempt_answer_attempt_question',
            'attempt_question',
            ['attemptQuestionId'], ['attemptQuestionId'],
            ondelete='CASCADE',
        )
        batch_op.drop_column('questionId')

    # 4. NOW we can safely drop quiz_question (FK is gone, no references)
    op.drop_table('quiz_question')

    # 5. Add defaultQuestionCount to quiz (server_default for existing 22 rows)
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'defaultQuestionCount',
            sa.Integer(),
            nullable=False,
            server_default='10',
        ))

    # 6. Add generationStatus + targetQuestionCount to quiz_attempt
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.add_column(sa.Column(
            'generationStatus',
            sa.String(length=16),
            nullable=False,
            server_default='pending',
        ))
        batch_op.add_column(sa.Column(
            'targetQuestionCount',
            sa.Integer(),
            nullable=False,
            server_default='10',
        ))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz_attempt', schema=None) as batch_op:
        batch_op.drop_column('targetQuestionCount')
        batch_op.drop_column('generationStatus')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.drop_column('defaultQuestionCount')

    with op.batch_alter_table('attempt_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('questionId', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('attempt_answer_ibfk_2'), 'quiz_question', ['questionId'], ['questionId'], ondelete='CASCADE')
        batch_op.drop_column('attemptQuestionId')

    op.create_table('quiz_question',
    sa.Column('questionId', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quizId', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orderIndex', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('stem', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=False),
    sa.Column('options', mysql.JSON(), nullable=False),
    sa.Column('correctIndex', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('explanation', mysql.TEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('points', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('(`correctIndex` between 0 and 3)', name=op.f('ck_correct_idx')),
    sa.CheckConstraint('(`points` >= 0)', name=op.f('ck_points_nonneg')),
    sa.ForeignKeyConstraint(['quizId'], ['quiz.quizId'], name=op.f('quiz_question_ibfk_1'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('questionId'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('quiz_question', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('uq_question_order'), ['quizId', 'orderIndex'], unique=True)
        batch_op.create_index(batch_op.f('ix_quiz_question_quizId'), ['quizId'], unique=False)

    with op.batch_alter_table('attempt_question', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attempt_question_attemptId'))

    op.drop_table('attempt_question')
    # ### end Alembic commands ###