"""cause_effect_diagram

Revision ID: d81d90e2d651
Revises: 729813a0518e
Create Date: 2026-06-06 23:03:23.555442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81d90e2d651'
down_revision = '729813a0518e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cause_effect_diagram',
    sa.Column('diagramId', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('formLevel', sa.Integer(), nullable=False),
    sa.Column('chapterId', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('mermaidSource', sa.Text(), nullable=False),
    sa.Column('generatedAt', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['formLevel', 'chapterId'], ['chapter.formLevel', 'chapter.chapterId'], name='fk_ced_chapter', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('diagramId'),
    sa.UniqueConstraint('formLevel', 'chapterId', name='uq_ced_chapter')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cause_effect_diagram')
    # ### end Alembic commands ###
